#全体
use_gpu: True
use_model: clip


#CLIPの設定
model:
  clip:
    base_model: ViT-B/32

data:
  data_dir: /content/drive/MyDrive/論文/package/data
  mathematical_model_list:
    - Turing
    - KT
    - Gray_Scott
    - PhaseField
    - Eden
    - DLA
    - L_system
    - Edwards_Wilkinson
  parameter_estimation_data:
    train: exp2_narrow_q0
    val: exp1_narrow_q0_val
  param_space_split_n: 
    - 10
    - 10

umap:
  n_neighbors: 50
  min_dist: 0.7
  mapper_name: mapper_nn_50_md_0.7.pickle
  randomseed: 123

dml:
  output_dim: 2
  batch_size: 32
  epoch: 100
  learning_rate: 0.001
  weight_decay: 0.001
  loss_margin: 0.1
  miner_epsilon: 0.2
  sampler_m: 4
  num_workers: 2

ngboost:
  modelname: ngb
  criterion: friedman_mse
  tree_max_depth: 3
  lattice_size: 0.005
  grid_num: 100
  parameter_n: 2
  parameter_list:
    - f_v
    - g_v
  learning_rate: 0.087
  n_estimators: 150